# Generated by Django 4.0.4 on 2023-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0101001001', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('owner', 'owner'), ('client', 'client')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
