# Generated by Django 4.0.4 on 2023-01-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_stationery_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationery',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
