# Generated by Django 4.0.4 on 2023-01-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_create_by_stationery_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='no_copies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='pages',
            field=models.IntegerField(),
        ),
    ]
