# Generated by Django 4.0.4 on 2023-01-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_document_no_copies_alter_document_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='staionery_id',
            new_name='stationery_id',
        ),
    ]
